const geographicData = {
  continents: [
    "Africa",
    "Antarctica",
    "Asia",
    "Australia",
    "Europe",
    "North America",
    "South America",
  ],
  worldCities: [
    "Tokyo",
    "Delhi",
    "Shanghai",
    "Dhaka",
    "Sao Paulo",
    "Cairo",
    "Mexico City",
    "Beijing",
    "Mumbai",
    "Osaka",
    "Chongqing",
    "Karachi",
    "Kinshasa",
    "Lagos",
    "Istanbul",
    "Buenos Aires",
    "Kolkata",
    "Manila",
    "Guangzhou",
    "Tianjin",
    "Lahore",
    "Bangalore",
    "Rio de Janeiro",
    "Shenzhen",
    "Moscow",
    "Chennai",
    "Bogota",
    "Jakarta",
    "Lima",
    "Paris",
    "Bangkok",
    "Hyderabad",
    "Seoul",
    "Nanjing",
    "Chengdu",
    "London",
    "Luanda",
    "Tehran",
    "Ho Chi Minh City",
    "Nagoya",
    "Xi-an",
    "Ahmedabad",
    "Wuhan",
    "Kuala Lumpur",
    "Hangzhou",
    "Suzhou",
    "Surat",
    "Dar es Salaam",
    "New York City",
    "Baghdad",
    "Shenyang",
    "Riyadh",
    "Hong Kong",
    "Foshan",
    "Dongguan",
    "Pune",
    "Santiago",
    "Haerbin",
    "Madrid",
    "Khartoum",
    "Toronto",
    "Johannesburg",
    "Belo Horizonte",
    "Dalian",
    "Singapore",
    "Qingdao",
    "Zhengzhou",
    "Ji nan Shandong",
    "Abidjan",
    "Barcelona",
    "Yangon",
    "Addis Ababa",
    "Alexandria",
    "Saint Petersburg",
    "Nairobi",
    "Chittagong",
    "Guadalajara",
    "Fukuoka",
    "Ankara",
    "Hanoi",
    "Melbourne",
    "Monterrey",
    "Sydney",
    "Changsha",
    "Urumqi",
    "Cape Town",
    "Jiddah",
    "Brasilia",
    "Kunming",
    "Changchun",
    "Kabul",
    "Hefei",
    "Yaounde",
    "Ningbo",
    "Shantou",
    "New Taipei",
    "Tel Aviv",
    "Kano",
    "Shijiazhuang",
    "Montreal",
    "Rome",
    "Jaipur",
    "Recife",
    "Nanning",
    "Fortaleza",
    "Kozhikode",
    "Porto Alegre",
    "Taiyuan Shanxi",
    "Douala",
    "Ekurhuleni",
    "Malappuram",
    "Medellin",
    "Changzhou",
    "Kampala",
    "Antananarivo",
    "Lucknow",
    "Abuja",
    "Nanchang",
    "Wenzhou",
    "Xiamen",
    "Ibadan",
    "Fuzhou Fujian",
    "Salvador",
    "Casablanca",
    "Tangshan Hebei",
    "Kumasi",
    "Curitiba",
    "Bekasi",
    "Faisalabad",
    "Los Angeles",
    "Guiyang",
    "Port Harcourt",
    "Thrissur",
    "Santo Domingo",
    "Berlin",
    "Asuncion",
    "Dakar",
    "Kochi",
    "Wuxi",
    "Busan",
    "Campinas",
    "Mashhad",
    "Sanaa",
    "Puebla",
    "Indore",
    "Lanzhou",
    "Ouagadougou",
    "Kuwait City",
    "Lusaka",
    "Kanpur",
    "Durban",
    "Guayaquil",
    "Pyongyang",
    "Milan",
    "Guatemala City",
    "Athens",
    "Depok",
    "Izmir",
    "Nagpur",
    "Surabaya",
    "Handan",
    "Coimbatore",
    "Huaian",
    "Port-au-Prince",
    "Zhongshan",
    "Dubai",
    "Bamako",
    "Mbuji-Mayi",
    "Kiev",
    "Lisbon",
    "Weifang",
    "Caracas",
    "Thiruvananthapuram",
    "Algiers",
    "Shizuoka",
    "Lubumbashi",
    "Cali",
    "Goiania",
    "Pretoria",
    "Shaoxing",
    "Incheon",
    "Yantai",
    "Zibo",
    "Huizhou",
    "Manchester",
    "Taipei",
    "Mogadishu",
    "Brazzaville",
    "Accra",
    "Bandung",
    "Damascus",
    "Birmingham",
    "Vancouver",
    "Toluca de Lerdo",
    "Luoyang",
    "Sapporo",
    "Chicago",
    "Tashkent",
    "Patna",
    "Bhopal",
    "Tangerang",
    "Nantong",
    "Brisbane",
    "Tunis",
    "Peshawar",
    "Medan",
    "Gujranwala",
    "Baku",
    "Hohhot",
    "San Juan",
    "Belem",
    "Rawalpindi",
    "Agra",
    "Manaus",
    "Kannur",
    "Beirut",
    "Maracaibo",
    "Liuzhou",
    "Visakhapatnam",
    "Baotou",
    "Vadodara",
    "Barranquilla",
    "Phnom Penh",
    "Sendai",
    "Taoyuan",
    "Xuzhou",
    "Houston",
    "Aleppo",
    "Tijuana",
    "Esfahan",
    "Nashik",
    "Vijayawada",
    "Amman",
    "Putian",
    "Multan",
    "Grande Vitoria",
    "Wuhu Anhui",
    "Mecca",
    "Kollam",
    "Naples",
    "Daegu",
    "Conakry",
    "Yangzhou",
    "Havana",
    "Taizhou Zhejiang",
    "Baoding",
    "Perth",
    "Brussels",
    "Linyi Shandong",
    "Bursa",
    "Rajkot",
    "Minsk",
    "Hiroshima",
    "Haikou",
    "Daqing",
    "Lome",
    "Lianyungang",
    "Yancheng Jiangsu",
    "Panama City",
    "Almaty",
    "Semarang",
    "Valencia",
    "Davao City",
    "Vienna",
    "Rabat",
    "Ludhiana",
    "Quito",
    "Benin City",
    "La Paz",
    "Baixada Santista",
    "West Yorkshire",
    "Can Tho",
    "Zhuhai",
    "Leon de los Aldamas",
    "Quanzhou",
    "Matola",
    "Datong",
    "Sharjah",
    "Madurai",
    "Raipur",
    "Adana",
    "Santa Cruz",
    "Palembang",
    "Mosul",
    "Cixi",
    "Meerut",
    "Gaziantep",
    "La Laguna",
    "Batam",
    "Turin",
    "Warsaw",
    "Jiangmen",
    "Varanasi",
    "Hamburg",
    "Montevideo",
    "Budapest",
    "Lyon",
    "Xiangyang",
    "Bucharest",
    "Yichang",
    "Yinchuan",
    "Shiraz",
    "Kananga",
    "Srinagar",
    "Monrovia",
    "Tiruppur",
    "Jamshedpur",
    "Suqian",
    "Aurangabad",
    "Qinhuangdao",
    "Stockholm",
    "Anshan",
    "Glasgow",
    "Xining",
    "Makassar",
    "Hengyang",
    "Novosibirsk",
    "Ulaanbaatar",
    "Onitsha",
    "Jilin",
    "Anyang",
    "Auckland",
    "Tabriz",
    "Muscat",
    "Calgary",
    "Phoenix",
    "Qiqihaer",
    "N-Djamena",
    "Marseille",
    "Cordoba",
    "Jodhpur",
    "Kathmandu",
    "Rosario",
    "Tegucigalpa",
    "Ciudad Juarez",
    "Harare",
    "Karaj",
    "Medina",
    "Jining Shandong",
    "Abu Dhabi",
    "Munich",
    "Ranchi",
    "Daejon",
    "Zhangjiakou",
    "Edmonton",
    "Mandalay",
    "Gaoxiong",
    "Kota",
    "Natal",
    "Nouakchott",
    "Jabalpur",
    "Huainan",
    "Grande Sao Luis",
    "Asansol",
    "Philadelphia",
    "Yekaterinburg",
    "Gwangju",
    "Yiwu",
    "Chaozhou",
    "San Antonio",
    "Gwalior",
    "Ganzhou",
    "Homs",
    "Niamey",
    "Mombasa",
    "Allahabad",
    "Basra",
    "Kisangani",
    "San Jose",
    "Amritsar",
    "Taizhou Jiangsu",
    "Chon Buri",
    "Jiaxing",
    "Weihai",
    "Hai Phong",
    "Ottawa",
    "Zurich",
    "Taian Shandong",
    "Queretaro",
    "Joao Pessoa",
    "Kaifeng",
    "Cochabamba",
    "Konya",
    "Liuyang",
    "Liuan",
    "Rizhao",
    "Kharkiv",
    "Dhanbad",
    "Nanchong",
    "Dongying",
    "Belgrade",
    "Zunyi",
    "Zhanjiang",
    "Bucaramanga",
    "Uyo",
    "Copenhagen",
    "San Diego",
    "Shiyan",
    "Taizhong",
    "Bareilly",
    "Pointe-Noire",
    "Adelaide",
    "Suweon",
    "Mwanza",
    "Mianyang Sichuan",
    "Samut Prakan",
    "Maceio",
    "Qom",
    "Antalya",
    "Joinville",
    "Tengzhou",
    "Yingkou",
    "Ad-Dammam",
    "Tanger",
    "Freetown",
    "Helsinki",
    "Aligarh",
    "Moradabad",
    "Pekan Baru",
    "Maoming",
    "Lilongwe",
    "Porto",
    "Prague",
    "Astana",
    "Jieyang",
    "Fushun Liaoning",
    "Mysore",
    "Abomey-Calavi",
    "Ruian",
    "Fes",
    "Port Elizabeth",
    "Florianopolis",
    "Ahvaz",
    "Bukavu",
    "Dallas",
    "Nnewi",
    "Kazan",
    "Jinhua",
    "San Luis Potosi",
    "Baoji",
    "Durg-Bhilainagar",
    "Bhubaneswar",
    "Kigali",
    "Sofia",
    "Pingdingshan Henan",
    "Dublin",
    "Puning",
    "Chifeng",
    "Zhuzhou",
    "Bujumbura",
    "Zhenjiang Jiangsu",
    "Liupanshui",
    "Barquisimeto",
    "Islamabad",
    "Huaibei",
    "Tasikmalaya",
    "Maracay",
    "Bogor",
    "Da Nang",
    "Nanyang Henan",
    "Nizhniy Novgorod",
    "Xiangtan Hunan",
    "Pizhou",
    "Tiruchirappalli",
    "Chelyabinsk",
    "Mendoza",
    "Luohe",
    "Xiongan",
    "Chandigarh",
    "Merida",
    "Jinzhou",
    "Benxi",
    "Binzhou",
    "Aba",
    "Chiang Mai",
    "Bazhong",
    "Quetta",
    "Kaduna",
    "Guilin",
    "Saharanpur",
    "Hubli-Dharwad",
    "Yueqing",
    "Guwahati",
    "Mexicali",
    "Salem",
    "Maputo",
    "Tripoli",
    "Haifa",
    "Bandar Lampung",
    "Bobo-Dioulasso",
    "Amsterdam",
    "Shimkent",
    "Omsk",
    "Aguascalientes",
    "Hargeysa",
    "Krasnoyarsk",
    "Xinxiang",
  ],
  countries: [
    "India",
    "China",
    "United States",
    "Indonesia",
    "Pakistan",
    "Nigeria",
    "Brazil",
    "Bangladesh",
    "Russia",
    "Ethiopia",
    "Mexico",
    "Japan",
    "Egypt",
    "Philippines",
    "DR Congo",
    "Vietnam",
    "Iran",
    "Turkey",
    "Germany",
    "Thailand",
    "United Kingdom",
    "Tanzania",
    "France",
    "South Africa",
    "Italy",
    "Kenya",
    "Myanmar",
    "Colombia",
    "South Korea",
    "Sudan",
    "Uganda",
    "Spain",
    "Algeria",
    "Iraq",
    "Argentina",
    "Afghanistan",
    "Yemen",
    "Canada",
    "Poland",
    "Morocco",
    "Angola",
    "Ukraine",
    "Uzbekistan",
    "Malaysia",
    "Mozambique",
    "Ghana",
    "Peru",
    "Saudi Arabia",
    "Madagascar",
    "Ivory Coast",
    "Nepal",
    "Cameroon",
    "Venezuela",
    "Niger",
    "Australia",
    "North Korea",
    "Syria",
    "Mali",
    "Burkina Faso",
    "Taiwan",
    "Sri Lanka",
    "Malawi",
    "Zambia",
    "Kazakhstan",
    "Chad",
    "Chile",
    "Romania",
    "Somalia",
    "Senegal",
    "Guatemala",
    "Netherlands",
    "Ecuador",
    "Cambodia",
    "Zimbabwe",
    "Guinea",
    "Benin",
    "Rwanda",
    "Burundi",
    "Bolivia",
    "Tunisia",
    "South Sudan",
    "Haiti",
    "Belgium",
    "Jordan",
    "Dominican Republic",
    "United Arab Emirates",
    "Cuba",
    "Honduras",
    "Czech Republic",
    "Sweden",
    "Tajikistan",
    "Papua New Guinea",
    "Portugal",
    "Azerbaijan",
    "Greece",
    "Hungary",
    "Togo",
    "Israel",
    "Austria",
    "Belarus",
    "Switzerland",
    "Sierra Leone",
    "Laos",
    "Turkmenistan",
    "Hong Kong",
    "Libya",
    "Kyrgyzstan",
    "Paraguay",
    "Nicaragua",
    "Bulgaria",
    "Serbia",
    "El Salvador",
    "Republic of the Congo",
    "Denmark",
    "Singapore",
    "Lebanon",
    "Finland",
    "Liberia",
    "Norway",
    "Slovakia",
    "Palestine",
    "Central African Republic",
    "Oman",
    "Ireland",
    "New Zealand",
    "Mauritania",
    "Costa Rica",
    "Kuwait",
    "Panama",
    "Croatia",
    "Georgia",
    "Eritrea",
    "Mongolia",
    "Uruguay",
    "Puerto Rico",
    "Bosnia and Herzegovina",
    "Qatar",
    "Moldova",
    "Namibia",
    "Armenia",
    "Lithuania",
    "Jamaica",
    "Albania",
    "Gambia",
    "Gabon",
    "Botswana",
    "Lesotho",
    "Guinea-Bissau",
    "Slovenia",
    "Equatorial Guinea",
    "Latvia",
    "North Macedonia",
    "Bahrain",
    "Trinidad and Tobago",
    "Timor-Leste",
    "Estonia",
    "Cyprus",
    "Mauritius",
    "Eswatini",
    "Djibouti",
    "Fiji",
    "Reunion",
    "Comoros",
    "Guyana",
    "Solomon Islands",
    "Bhutan",
    "Macau",
    "Luxembourg",
    "Montenegro",
    "Suriname",
    "Western Sahara",
    "Malta",
    "Maldives",
    "Cape Verde",
    "Brunei",
    "Belize",
    "Bahamas",
    "Iceland",
    "Guadeloupe",
    "Martinique",
    "Vanuatu",
    "Mayotte",
    "French Guiana",
    "New Caledonia",
    "Barbados",
    "French Polynesia",
    "Sao Tome and Principe",
    "Samoa",
    "Curacao",
    "Saint Lucia",
    "Guam",
    "Kiribati",
    "Seychelles",
    "Grenada",
    "Micronesia",
    "Aruba",
    "Tonga",
    "Jersey",
    "Saint Vincent and the Grenadines",
    "Antigua and Barbuda",
    "United States Virgin Islands",
    "Isle of Man",
    "Andorra",
    "Cayman Islands",
    "Dominica",
    "Bermuda",
    "Guernsey",
    "Greenland",
    "Faroe Islands",
    "Saint Kitts and Nevis",
    "American Samoa",
    "Turks and Caicos Islands",
    "Northern Mariana Islands",
    "Sint Maarten",
    "Liechtenstein",
    "British Virgin Islands",
    "Gibraltar",
    "Monaco",
    "Marshall Islands",
    "San Marino",
    "Saint Martin",
    "Palau",
    "Anguilla",
    "Cook Islands",
    "Nauru",
    "Wallis and Futuna",
    "Saint Barthelemy",
    "Tuvalu",
    "Saint Pierre and Miquelon",
    "Montserrat",
    "Falkland Islands",
    "Tokelau",
    "Niue",
    "Vatican City",
  ],
  usStates: [
    "California",
    "Texas",
    "Florida",
    "New York",
    "Pennsylvania",
    "Illinois",
    "Ohio",
    "Georgia",
    "North Carolina",
    "Michigan",
    "New Jersey",
    "Virginia",
    "Washington",
    "Arizona",
    "Tennessee",
    "Massachusetts",
    "Indiana",
    "Missouri",
    "Maryland",
    "Wisconsin",
    "Colorado",
    "Minnesota",
    "South Carolina",
    "Alabama",
    "Louisiana",
    "Kentucky",
    "Oregon",
    "Oklahoma",
    "Connecticut",
    "Utah",
    "Iowa",
    "Nevada",
    "Arkansas",
    "Kansas",
    "Mississippi",
    "New Mexico",
    "Idaho",
    "Nebraska",
    "West Virginia",
    "Hawaii",
    "New Hampshire",
    "Maine",
    "Montana",
    "Rhode Island",
    "Delaware",
    "South Dakota",
    "North Dakota",
    "Alaska",
    "Vermont",
    "Wyoming",
  ],
  usCities: [
    "New York City",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "Jacksonville",
    "Fort Worth",
    "Austin",
    "San Jose",
    "Charlotte",
    "Columbus",
    "Indianapolis",
    "San Francisco",
    "Seattle",
    "Denver",
    "Oklahoma City",
    "Nashville",
    "Washington",
    "El Paso",
    "Las Vegas",
    "Boston",
    "Detroit",
    "Portland",
    "Louisville",
    "Memphis",
    "Baltimore",
    "Albuquerque",
    "Milwaukee",
    "Tucson",
    "Fresno",
    "Sacramento",
    "Atlanta",
    "Mesa",
    "Kansas City",
    "Colorado Springs",
    "Raleigh",
    "Omaha",
    "Miami",
    "Virginia Beach",
    "Long Beach",
    "Oakland",
    "Minneapolis",
    "Bakersfield",
    "Tulsa",
    "Tampa",
    "Arlington",
    "Aurora",
    "Wichita",
    "Cleveland",
    "New Orleans",
    "Henderson",
    "Honolulu",
    "Anaheim",
    "Orlando",
    "Riverside",
    "Lexington",
    "Stockton",
    "Irvine",
    "Corpus Christi",
    "Cincinnati",
    "Santa Ana",
    "Greensboro",
    "Pittsburgh",
    "Newark",
    "St. Paul",
    "Durham",
    "Lincoln",
    "North Las Vegas",
    "Jersey City",
    "Plano",
    "Anchorage",
    "Madison",
    "Chandler",
    "Reno",
    "Gilbert",
    "St. Louis",
    "Chula Vista",
    "Buffalo",
    "Fort Wayne",
    "Lubbock",
    "St. Petersburg",
    "Toledo",
    "Laredo",
    "Port St. Lucie",
    "Glendale",
    "Chesapeake",
    "Winston-Salem",
    "Irving",
    "Scottsdale",
    "Enterprise",
    "Garland",
    "Boise City",
    "Cape Coral",
    "Frisco",
    "Richmond",
    "Spokane",
    "Norfolk",
    "Huntsville",
    "Spring Valley",
    "Fremont",
    "San Bernardino",
    "Tacoma",
    "Santa Clarita",
    "Hialeah",
    "Modesto",
    "McKinney",
    "Fontana",
    "Baton Rouge",
    "Moreno Valley",
    "Salt Lake City",
    "Sioux Falls",
    "Fayetteville",
    "Des Moines",
    "Worcester",
    "Yonkers",
    "Rochester",
    "Little Rock",
    "Grand Prairie",
    "Tallahassee",
    "Amarillo",
    "Peoria",
    "Augusta",
    "Knoxville",
    "Sunrise Manor",
    "Vancouver",
    "Oxnard",
    "Overland Park",
    "Grand Rapids",
    "Birmingham",
    "Montgomery",
    "Tempe",
    "Brownsville",
    "Providence",
    "Huntington Beach",
    "Chattanooga",
    "Akron",
    "Clarksville",
    "Fort Lauderdale",
    "Ontario",
    "Paradise",
    "Newport News",
    "Cary",
    "Mobile",
    "Elk Grove",
    "Eugene",
    "Salem",
    "Santa Rosa",
    "Shreveport",
    "Rancho Cucamonga",
    "Pembroke Pines",
    "Springfield",
    "Fort Collins",
    "Murfreesboro",
    "Oceanside",
    "Garden Grove",
    "Denton",
    "Lancaster",
    "Surprise",
    "Roseville",
    "Killeen",
    "Corona",
    "Palmdale",
    "Salinas",
    "Charleston",
    "Macon-Bibb County",
    "Lakewood",
    "Paterson",
    "Hollywood",
    "Alexandria",
    "Hayward",
    "Bellevue",
    "Sunnyvale",
    "Joliet",
    "Naperville",
    "Olathe",
    "Bridgeport",
    "McAllen",
    "Savannah",
    "Escondido",
    "Gainesville",
    "Mesquite",
    "Waco",
    "Visalia",
    "Thornton",
    "Rockford",
    "Syracuse",
    "Pasadena",
    "Columbia",
    "Pomona",
    "Palm Bay",
  ],
};
